### ISSUE TITLE
Telebot not added as a dependency

### ISSUE THREAD

**Issue by DarkHole1** [Antcating/telegram_parser#3]
**Describe the bug**
Telebot used but not added as a dependency

**To Reproduce**
Simplest way to check:
1. Create venv (for example with pipenv)
2. Install dependencies
3. Start console.py

**Expected behavior**
Telebot should be added to dependecies list

**Screenshots**
![image](https://user-images.githubusercontent.com/15856734/129944580-860dc1d8-2318-42e2-8372-ffdd949735bf.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by Antcating** [comment]
Fixed
